image: docker:19.03.12

stages:
  - build
  - deploy

variables:
  CONTAINER_NAME: discovery-service

build:
  image: gradle:6.9.0-jdk11
  stage: build
  script:
    - gradle build -x test
  artifacts:
    paths:
      - build/libs/*.jar
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    policy: push
    paths:
      - build/libs/*.jar

build-docker-image:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    policy: pull
    paths:
      - build/libs/*.jar
  script:
    - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_HUB_ID/$IMAGE_NAME .
    - docker push $DOCKER_HUB_ID/$IMAGE_NAME

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_HUB_ID/$IMAGE_NAME
    - "{ docker stop $CONTAINER_NAME; docker rm $CONTAINER_NAME; } || true"
    - "docker run -d -p $DISCOVERY_SERVICE_PORT:$DISCOVERY_SERVICE_PORT \
    --name $CONTAINER_NAME \
    -e EUREKA_SERVER_URL=$EUREKA_SERVER_URL \
    $DOCKER_HUB_ID/$IMAGE_NAME"